### ISSUE TITLE
Subscribe error during startup of spring boot application

### ISSUE THREAD

**Issue by hasanmk52** [deviceinsight/kafka-health-check#16]
I am using the default configuration and also created the kafka health check topic manually with command: 

`kafka-topics.sh --zookeeper 127.0.0.1:2181 --topic health-checks --create --partitions 1 --replication-factor 1`

But getting the below error. Any reason as to why we get this:

```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'kafkaConsumingHealthIndicator': Invocation of init method failed; nested exception is org.springframework.beans.factory.BeanInitializationException: Subscription to kafka failed, topic=health-checks
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:160) ~[spring-beans-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:415) ~[spring-beans-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1786) ~[spring-beans-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:594) ~[spring-beans-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:516) ~[spring-beans-5.2.8.RELEASE.jar:5.2.8.RELEASE]
```

**Comment by ezienecker** [comment]
Make sure that the following dependency is provided by the service that uses the kafka-health-check.

```
<dependency>
	<groupId>org.springframework.kafka</groupId>
	<artifactId>spring-kafka</artifactId>
	<scope>provided</scope>
</dependency>
```

**Comment by ezienecker** [comment]
I’m closing this issue because it has been inactive for a few months. Please reopen if you still encounter this issue.

**Comment by hasanmk52** [comment]
Sorry for not responding, but I have given the dependency and still get the error.

**Comment by pvorb** [comment]
Is your service able to read or write kafka messages in general? It's a bit difficult to give you better advice without more context.
